fn throwingFunc() throws {
    return
}
fn foo() {
    do {
try throwingFunc()
} catch {
<#code#>
}
}
